accounts/urls.py
from django.urls import path, include

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login', views.LoginView.as_view(), name='login'),
    path('register', views.RegisterView.as_view(), name='register'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('users/', include([
        path('my-courses', views.EnrolledCoursesListView.as_view(), name='enrolled-courses'),
        path('my-courses/<slug:slug>/view', views.StartLessonView.as_view(), name='course-lessons'),
        path('my-courses/<slug:slug>/lessons/<int:id>', views.LessonView.as_view(), name='course-lessons-single'),
        path('profile', views.ProfileUpdateView.as_view(), name='my-profile'),
    ])),
]

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<slug:slug>/', views.cart_add, name='cart_add'),
    path('remove/<slug:slug>', views.cart_remove, name='cart_remove'),
    path('checkout', views.cart_checkout, name='cart_checkout'),
]

courses/urls.py
from django.urls import path
from .views import *

app_name = 'courses'

urlpatterns = [
    path('courses/<slug:slug>', CourseDetailView.as_view(), name='course-details'),
    path('courses/<slug:slug>/category', CoursesByCategoryListView.as_view(), name='course-by-category'),
]

elearnplatform/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from elearnplatform import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('', include('accounts.urls')),
    path('', include('elearn.urls')),
    path('', include('courses.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils.text import slugify
from django.utils.timezone import now

from accounts.models import User


class Category(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=200, unique=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Category, self).save(*args, **kwargs)


class Course(models.Model):
    title = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    slug = models.SlugField(max_length=200, unique=True, primary_key=True, auto_created=False)
    short_description = models.TextField(blank=False, max_length=60)
    description = models.TextField(blank=False)
    outcome = models.CharField(max_length=200)
    requirements = models.CharField(max_length=200)
    language = models.CharField(max_length=200)
    price = models.FloatField(validators=[MinValueValidator(9.99)])
    level = models.CharField(max_length=20)
    thumbnail = models.ImageField(upload_to='thumbnails/')
    video_url = models.CharField(max_length=100)
    is_published = models.BooleanField(default=True)
    created_at = models.DateTimeField(default=now)
    updated_at = models.DateTimeField(default=now)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Course, self).save(*args, **kwargs)


class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='lessons')
    title = models.CharField(max_length=100)
    duration = models.FloatField(validators=[MinValueValidator(0.30), MaxValueValidator(30.00)])
    video_url = models.CharField(max_length=100)
    created_at = models.DateTimeField(default=now)
    updated_at = models.DateTimeField(default=now)

    def __str__(self):
        return self.title

courses/views.py
from django.http import Http404
from django.shortcuts import render
from django.views.generic import DetailView, ListView

from cart.cart import Cart
from courses.models import Course, Category
from elearn.models import Enroll


class CourseDetailView(DetailView):
    model = Course
    template_name = 'courses/details.html'
    context_object_name = 'course'

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()

        slug = self.kwargs.get(self.slug_url_kwarg)
        slug_field = self.get_slug_field()
        queryset = queryset.filter(**{slug_field: slug})
        try:
            # Get the single item from the filtered queryset
            obj = queryset.get()
        except queryset.model.DoesNotExist:
            raise Http404("No %(verbose_name)s found matching the query" %
                          {'verbose_name': self.model._meta.verbose_name})
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        course = self.get_object(self.get_queryset())
        if self.request.user.is_authenticated:
            if Enroll.objects.filter(course=course, user_id=self.request.user.id).exists():
                context['is_enrolled'] = True
            else:
                cart = Cart(self.request)
                context['is_in_cart'] = cart.has_course(course)
        else:
            cart = Cart(self.request)
            context['is_in_cart'] = cart.has_course(course)
        return context


class CoursesByCategoryListView(ListView):
    model = Course
    template_name = 'courses/courses_by_category.html'
    context_object_name = 'courses'

    def get_queryset(self):
        category = Category.objects.get(slug=self.kwargs['slug'])
        return self.model.objects.filter(category_id=category.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = Category.objects.get(slug=self.kwargs['slug'])
        context['category'] = category
        context['categories'] = Category.objects.all()
        return context

templates/courses/courses_by_category.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block content %}

    <section class="category-header-area">
        <div class="container-lg">
            <div class="row">
                <div class="col">
                    <nav>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="/">
                                    <i class="fas fa-home"></i>
                                </a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="#">
                                    {{ category.title }}
                                </a>
                            </li>
                        </ol>
                    </nav>
                    <h1 class="category-name">
                        {{ category.title }}
                    </h1>
                </div>
            </div>
        </div>
    </section>

    <section class="category-course-list-area">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="category-filter-box filter-box clearfix">
                        <a href="" class="btn btn-outline-secondary all-btn">All</a>

                        <div class="btn-group category-list">
                            <a class="btn btn-outline-secondary dropdown-toggle" href="#" data-toggle="dropdown">
                                Category List
                            </a>
                            <div class="dropdown-menu">
                                {% for category in categories %}
                                    <a class="dropdown-item" href="{% url 'courses:course-by-category' category.slug %}">
                                        {{ category.title }}
                                    </a>
                                {% endfor %}
                            </div>
                        </div>

                    </div>
                    <div class="category-course-list">
                        <ul>
                            {% for course in courses %}
                                <li>
                                    <div class="course-box-2">
                                        <div class="course-details">
                                            <a href="{% url 'courses:course-details' course.slug %}"
                                               class="course-title">{{ course.title }}</a>
                                            {#                                            {{--<a href="" class="course-instructor">--}}#}
                                            {#                                                {{--<span class="instructor-name">first_name last_name</span>--}}#}
                                            {#                                                {{-----}}#}
                                            {#                                            {{--</a>--}}#}
                                            <div class="course-subtitle">
                                                {{ course.short_description }}
                                            </div>
                                            <div class="course-meta">
                                                <span class="">
                                                    <i class="fas fa-play-circle"></i>
                                                    {{ course.lessons.count }} Lessons
                                                </span>
                                                <span class="">
                                                    <i class="far fa-clock"></i>
                                                    3 hours
                                                </span>
                                                <span class="">
                                                    <i class="fas fa-closed-captioning"></i>English
                                                </span>
                                            </div>
                                        </div>
                                        <div class="course-price-rating">
                                            <div class="course-price">
                                                <span class="current-price">${{ course.price }}</span>
                                                {#                                                {{--<span class="original-price">$300</span>--}}#}
                                            </div>
                                            <div class="rating">
                                                <i class="fas fa-star filled"></i>
                                                <i class="fas fa-star filled"></i>
                                                <i class="fas fa-star filled"></i>
                                                <i class="fas fa-star"></i>
                                                <span class="d-inline-block average-rating">5</span>
                                            </div>
                                            <div class="rating-number">
                                                33 Ratings
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <nav>
                        {#                        {{ $courses->links() }}#}
                    </nav>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/courses/details.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load humanize %}
{% load total_minutes %}

{% block content %}

    <section class="course-header-area">
        <div class="container">
            <div class="row align-items-end">
                <div class="col-lg-8">
                    <div class="course-header-wrap">
                        <h1 class="title">{{ course.title }}</h1>
                        <p class="subtitle">{{ course.short_description|truncatewords:20 }}</p>
                    </div>
                </div>
                <div class="col-lg-4">

                </div>
            </div>
        </div>
    </section>

    <section class="course-content-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">

                    <div class="what-you-get-box">
                        <div class="what-you-get-title">What i will learn?</div>
                        <ul class="what-you-get__items">
                            <li>{{ course.outcome }}</li>
                        </ul>
                    </div>
                    <br>
                    <div class="course-curriculum-box">
                        <div class="course-curriculum-title clearfix">
                            <div class="title float-left">Lessons for this course</div>
                            <div class="float-right">
                                <span class="total-lectures">
                                    {{ course.lessons.count }} lessons
                                </span>
                                <span class="total-time">
                                    2 hours
                                </span>
                            </div>
                        </div>
                        <div class="course-curriculum-accordion">

                            <div class="lecture-group-wrapper">
                                <div class="lecture-group-title clearfix" data-toggle="collapse"
                                     data-target="#collapse"
                                     aria-expanded="false">
                                    <div class="title float-left">
                                        Lessons
                                    </div>
                                    <div class="float-right">
                                        <span class="total-lectures">
                                             {{ course.lessons.count }} lessons
                                        </span>
                                        <span class="total-time">
                                            {{ course.lessons|total_minutes | floatformat:2 }} minute
                                        </span>
                                    </div>
                                </div>

                                <div id="collapse" class="lecture-list collapse">
                                    <ul>
                                        {% for lesson in course.lessons.all %}
                                            <li class="lecture has-preview">
                                                <span class="lecture-title">{{ lesson.title }}</span>
                                                <span class="lecture-time float-right">{{ lesson.duration | floatformat:2 }}</span>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="requirements-box">
                        <div class="requirements-title">Requirements</div>
                        <div class="requirements-content">
                            <ul class="requirements__list">
                                <li>{{ course.requirements }}</li>
                            </ul>
                        </div>
                    </div>
                    <div class="description-box view-more-parent">
                        <div class="view-more" onclick="viewMore(this,'hide')">
                            + View More
                        </div>
                        <div class="description-title">Description</div>
                        <div class="description-content-wrap">
                            <div class="description-content">
                                {{ course.description }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="course-sidebar natural">
                        <div class="course-sidebar-text-box">
                            <div class="price">
                                <span class="current-price">
                                    $<span class="current-price">{{ course.price | floatformat:2 | intcomma }}</span></span>
                                <input type="hidden" id="total_price_of_checking_out" value="{{ course.price | floatformat:2 }}">
                            </div>

                            {#                            {{ --<div class="buy-btns">--}}#}
                            {#                            {{ --<button class="btn btn-buy-now" type="button">Already purchased</button>--}}#}
                            {#                            {{ --</div>--}}#}
                            <div class="buy-btns">
                                {% if is_enrolled %}
                                    <button class="btn btn-add-cart" type="button"
                                            style="background-color: #00796b; border-color: #08796f; color: #ffffff">
                                        Go to course
                                    </button>
                                {% else %}
                                    {% if is_in_cart %}
                                        {#                                    <a href="" class="btn btn-buy-now" id="course_2" onclick="handleBuyNow(this)">Buy#}
                                        {#                                        now</a>#}
                                        <button class="btn btn-add-cart" type="button"
                                                style="background-color: #0099ff; border-color: #0099ff; color: #ffffff">
                                            Added to cart
                                        </button>
                                    {% else %}
                                        <form action="{% url 'cart:cart_add' course.slug %}" method="post">
                                            {% csrf_token %}
                                            <input type="hidden" value="" name="course_id">
                                            <input type="hidden" value="" name="name">
                                            <input type="hidden" value="" name="price">
                                            <input type="hidden" value="1" name="quantity">

                                            <button class="btn btn-add-cart" type="submit" id="cart">Add to cart
                                            </button>
                                        </form>
                                    {% endif %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/courses/enrolled_courses.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block content %}

    <section class="category-header-area">
        <div class="container">
            <div class="row">
                <div class="col">
                    <h1 class="page-title">My Courses</h1>
                </div>
            </div>
        </div>
    </section>

    <section class="my-courses-area">
        <div class="container">
            <div class="row no-gutters" id="my_courses_area">
                {% for enroll in enrolls %}

                    <div class="col-lg-3">
                        <div class="course-box-wrap">
                            <div class="course-box">
                                <a href="">
                                </a>
                                <div class="course-details">
                                    <a href="">
                                        <h5 class="title">{{ enroll.course.title }}</h5>
                                    </a>
                                    <p class="instructors"></p>
                                    <div class="rating your-rating-box"
                                         data-toggle="modal" data-id="{{ enroll.course.id }}"
                                         data-target="#EditRatingModal">

                                        {#                                        @php#}
                                        {#                                        $my_rating = $enroll->course->review()['rating'];#}
                                        {#                                        @endphp#}
                                        {#                                        @for($i = 1; $i <= 5; $i++)#}
                                        {#                                        @if ($i <= $my_rating)#}
                                        {#                                        <i class="fas fa-star filled"></i>#}
                                        {#                                        @else#}
                                        {#                                        <i class="fas fa-star"></i>#}
                                        {#                                        @endif#}
                                        {#                                        @endfor#}


                                    </div>
                                </div>
                                <div class="row" style="padding: 5px;">
                                    <div class="col-md-6">
                                        <a href="{% url 'courses:course-details' enroll.course.slug %}" class="btn">Course
                                            Details</a>
                                    </div>
                                    <div class="col-md-6">
                                        <a href="{% url 'accounts:course-lessons' enroll.course.slug %}" class="btn">Start
                                            lesson</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>

{% endblock %}

{% block scripts %}

    <script>

        function courseModal(course_id) {
            {#alert($course_id);#}
            $('#course_id_for_rating').val(course_id);
        }

    </script>

{% endblock %}